# Generated by Django 5.2.13 on 2026-05-02 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purohit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('base_price', models.DecimalField(decimal_places=2, default=1100.0, help_text='Starting price for basic pujas', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('avg_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('total_reviews', models.IntegerField(default=0)),
                ('total_bookings', models.IntegerField(default=0)),
                ('base_area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purohits_based_here', to='core.area')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purohits', to='core.city')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='purohit_listing', to='accounts.purohitprofile')),
                ('service_areas', models.ManyToManyField(blank=True, related_name='serviced_by_purohits', to='core.area')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PurohitAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_available', models.BooleanField(default=True)),
                ('blocked_reason', models.CharField(blank=True, max_length=200, null=True)),
                ('purohit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='purohits.purohit')),
            ],
            options={
                'verbose_name_plural': 'Purohit Availabilities',
                'unique_together': {('purohit', 'date')},
            },
        ),
    ]
