# Generated by Django 5.1.4 on 2026-09-13 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purohits', '0006_service_offers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purohit',
            name='travel_note',
            field=models.CharField(blank=True, help_text='Shown when you accept travel requests, e.g. I come if devotee covers train + stay.', max_length=240),
        ),
    ]
