# Generated by Django 5.2.9 on 2026-05-03 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=13)),
                ('otp_code', models.CharField(max_length=6)),
                ('otp_type', models.CharField(choices=[('login', 'Login'), ('signup', 'Signup'), ('verification', 'Phone Verification')], default='login', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('attempts', models.IntegerField(default=0)),
                ('max_attempts', models.IntegerField(default=3)),
            ],
            options={
                'indexes': [models.Index(fields=['phone', '-created_at'], name='accounts_ot_phone_9473c1_idx'), models.Index(fields=['expires_at'], name='accounts_ot_expires_57ad4f_idx')],
            },
        ),
    ]
