# Generated by Django 5.2.9 on 2026-05-03 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_booking_complete_code_booking_start_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
