# Generated by Django 5.2.9 on 2026-07-04 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_reschedule_enhancements'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='bookinghistory',
            new_name='bookings_bo_booking_a35183_idx',
            old_name='bookings_bo_booking_created_idx',
        ),
        migrations.AlterField(
            model_name='booking',
            name='reschedule_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='reschedule_count',
            field=models.IntegerField(default=0, help_text='Number of rescheduled occurrences'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='reschedule_rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='reschedule_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookinghistory',
            name='new_value',
            field=models.CharField(blank=True, help_text='New value for changes', max_length=100),
        ),
        migrations.AlterField(
            model_name='bookinghistory',
            name='old_value',
            field=models.CharField(blank=True, help_text='Previous value for changes', max_length=100),
        ),
    ]
