# Generated by Django 5.2.13 on 2026-05-02 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('purohits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PujaCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('icon', models.CharField(help_text='Lucide icon name', max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Puja Categories',
            },
        ),
        migrations.CreateModel(
            name='Puja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField()),
                ('base_duration_hours', models.DecimalField(decimal_places=2, help_text='Approximate duration in hours', max_digits=4)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pujas', to='pujas.pujacategory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PurohitPujaPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('includes_samagri', models.BooleanField(default=False)),
                ('samagri_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('custom_description', models.TextField(blank=True, help_text="Purohit's own description of how they perform it")),
                ('puja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offered_by', to='pujas.puja')),
                ('purohit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puja_packages', to='purohits.purohit')),
            ],
            options={
                'unique_together': {('purohit', 'puja')},
            },
        ),
    ]
